# Data-Dam Configuration

rate = 5
duration = "100s"
Concurrent = 10
schemas = ["dam"]
op-weight = [4, 2, 1, 0]

[db-config]
verbose = true

[db-config.mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
enabled = true
